'use client';
import { AlertTriangle, Check, ExternalLink, RotateCcw } from 'lucide-react';
import RiskBadge from './RiskBadge';
import ScoreRing from './ScoreRing';

export default function ResultPanel({ scan, onReset }) {
  const { result } = scan;
  return <section className="result-panel" aria-live="polite"><div className={`result-hero ${result.level}`}><ScoreRing score={result.score} level={result.level} /><div><div className="verdict-badges"><RiskBadge level={result.level} />{result.intelligence && <span className={`intel-badge ${result.intelligence.mode}`}>{result.intelligence.mode === 'live' ? 'Live threat intelligence' : 'Local protection mode'}</span>}</div><h2>{result.verdict}</h2><p>{result.summary}</p></div></div>{result.intelligence && <div className="source-card"><div><span>DATA SOURCES</span><h3>{result.intelligence.mode === 'live' ? 'Live and local evidence' : 'Local evidence only'}</h3><p>{result.intelligence.note}</p></div><div className="provider-list">{result.intelligence.providers.length ? result.intelligence.providers.map((provider, index) => <div key={`${provider.provider}-${provider.url}-${index}`}><strong>{provider.provider === 'google-web-risk' ? 'Google Web Risk' : 'VirusTotal'}</strong><span className={provider.status}>{provider.status.replaceAll('_', ' ')}</span></div>) : <div><strong>No external URL lookup</strong><span>not applicable</span></div>}</div></div>}<div className="result-grid"><div className="evidence-card"><div className="section-heading"><div><span>Evidence</span><h3>Why SafePay reached this result</h3></div><b>{result.findings.length}</b></div>{result.findings.length ? <div className="finding-list">{result.findings.map((item, index) => <article className="finding" key={`${item.category}-${index}`}><span><AlertTriangle size={17} /></span><div><strong>{item.category}</strong><p>{item.evidence}</p></div><small>+{item.weight}</small></article>)}</div> : <div className="empty-evidence"><Check /><p>No strong warning pattern was detected.</p></div>}</div><aside className="action-card"><span>Recommended action</span><h3>What to do now</h3><ol>{result.actions.map((action) => <li key={action}><span><Check size={15} /></span>{action}</li>)}</ol><button className="outline-button" onClick={onReset}><RotateCcw size={16} />Check another</button></aside></div>{result.checkedUrls.length > 0 && <div className="checked-links"><h3>Links inspected</h3>{result.checkedUrls.map((item) => <div key={item.url}><ExternalLink size={16} /><span>{item.host || item.url}</span></div>)}</div>}<p className="disclaimer">{result.disclaimer}</p></section>;
}
