import Link from 'next/link';
import { ArrowRight, BadgeCheck, BellRing, CheckCircle2, FileImage, HeartHandshake, KeyRound, Link2, LockKeyhole, MessageSquareText, QrCode, ShieldCheck, ShoppingBag, Sparkles, Users } from 'lucide-react';
import Scanner from '@/components/Scanner';

const features = [
  { icon: MessageSquareText, title: 'Message intelligence', text: 'Check SMS, email, WhatsApp or social messages for manipulation and impersonation.' },
  { icon: Link2, title: 'Live-ready link checks', text: 'Inspect look-alike domains, unsafe patterns and known threats when Web Risk is configured.' },
  { icon: ShoppingBag, title: 'Complete deal check', text: 'Assess the seller, price, payment request and conversation together—not in isolation.' },
  { icon: FileImage, title: 'Screenshot OCR', text: 'Extract message text locally from PNG, JPG and WebP screenshots before analysis.' },
  { icon: QrCode, title: 'QR-code inspection', text: 'Decode QR content locally, then check embedded links or payment instructions.' },
  { icon: HeartHandshake, title: 'Recovery guidance', text: 'Get a clear action list if money or personal information was already shared.' },
];
const scams = ['Fake bank alert','Marketplace deposit','Gift-card payment','Crypto investment','Fake delivery text','Account takeover','Remote-access support','Prize and refund scam'];

export default function HomePage() {
  return <>
    <section className="hero"><div className="hero-orb" /><div className="eyebrow"><Sparkles size={15} />Your second opinion before every payment</div><h1>Check the entire deal.<br /><span>Not just the link.</span></h1><p>SafePay Guardian finds scam signals across messages, links, screenshots, seller behavior and payment requests—then explains what to do next.</p><div className="hero-actions"><Link className="primary-button" href="/scam-checker">Check something now <ArrowRight size={18} /></Link><Link className="text-button" href="/safety">Explore safety guide</Link></div><div className="trust-row"><span><ShieldCheck />Privacy-first</span><span><BadgeCheck />Evidence explained</span><span><Users />Made for families</span></div></section>
    <section className="home-scanner page-width"><div className="section-title centered"><span>FREE RISK CHECK</span><h2>Paste it. Upload it. Know the warning signs.</h2><p>Check text, email, links, transaction details, screenshots and QR codes from one private workspace.</p></div><Scanner compact /></section>
    <section className="feature-section page-width"><div className="section-title"><span>COMPLETE PROTECTION</span><h2>One place to check before you trust, click or pay</h2><p>Built around the complete transaction—not a mysterious yes-or-no answer.</p></div><div className="feature-grid six">{features.map(({ icon: Icon, title, text }, index) => <article key={title}><div className="feature-number">0{index + 1}</div><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="how-band"><div className="page-width"><div className="section-title centered"><span>HOW SAFEPAY WORKS</span><h2>Evidence before a decision</h2></div><div className="home-steps">{[['01','Share the context','Paste a message, link or full deal without sharing secrets.'],['02','Signals work together','Local rules, link intelligence and payment behavior produce a combined score.'],['03','Take the safest action','See the reasons, confidence and exact steps to follow next.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section className="deal-section page-width"><div><span>COMPLETE DEAL CHECKER</span><h2>A seller can look real while the payment path is dangerous.</h2><p>SafePay considers the listing, price, conversation, seller behavior and payment method together. This catches warning signs that a link-only checker can miss.</p><ul>{['Advance payment pressure','Moving off the marketplace','Fake courier or escrow story','OTP and verification-code requests'].map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul><Link href="/marketplace-scam-checker">Check a marketplace deal <ArrowRight/></Link></div><div className="deal-card"><small>DEAL RISK</small><strong>86<span>/100</span></strong><b>High risk — pause payment</b><p>Seller requests crypto deposit and wants to move the chat to Telegram.</p><div><i/>Irreversible payment</div><div><i/>Off-platform pressure</div><div><i/>Unrealistic discount</div></div></section>
    <section className="audience-section page-width"><article><ShoppingBag/><span>FOR BUYERS</span><h2>Verify before sending money</h2><p>Check the seller, listing, payment request and urgency before leaving buyer protection.</p></article><article><BadgeCheck/><span>FOR SELLERS</span><h2>Spot fake buyers and receipts</h2><p>Recognize overpayment, fake courier, OTP theft and account-takeover instructions.</p></article><article><BellRing/><span>FOR FAMILIES</span><h2>Ask someone you trust</h2><p>Family review and high-risk alerts are designed into the production account model.</p></article></section>
    <section className="scam-cloud page-width"><div className="section-title centered"><span>COMMON THREATS</span><h2>Built for the scams people actually receive</h2></div><div>{scams.map(item=><span key={item}>{item}</span>)}</div></section>
    <section className="privacy-section page-width"><div><LockKeyhole/></div><div><span>PRIVACY BY DESIGN</span><h2>Your safety check should not create a new privacy risk.</h2><p>Screenshot OCR and QR decoding happen in the browser. Stored previews are redacted for common emails, phone numbers, card patterns and explicit verification codes.</p></div><ul><li><CheckCircle2/>No OTP or password required</li><li><CheckCircle2/>Server-only threat keys</li><li><CheckCircle2/>Clear local/live mode label</li></ul></section>
    <section className="recovery-preview page-width"><KeyRound/><div><span>ALREADY PAID?</span><h2>Act quickly with a recovery checklist.</h2><p>Secure accounts, contact the payment provider, preserve evidence and report through verified official channels.</p></div><Link href="/recovery">Open recovery guide <ArrowRight/></Link></section>
    <section className="cta-band page-width"><div><span>STOP. CHECK. DECIDE.</span><h2>A thirty-second check can prevent a costly mistake.</h2></div><Link className="light-button" href="/scam-checker">Run a free check <ArrowRight /></Link></section>
  </>;
}
